#!/bin/sh

background_color="#2d2d2d"
#background_color="#333333"
foreground_color="#8c8c8c"

black="#000000"
black_alt="#262626"

red="#ad8585"
red_alt="#d6c2c2"

green="#7db67d"
green_alt="#85ad85"

yellow="#adad85"
yellow_alt="#d6d6c2"

blue="#545490"
blue_alt="#8585ad"

magenta="#ad85ad"
magenta_alt="#d6c2d6"

cyan="#85adad"
cyan_alt="#c2d6d6"

white="#d9d9d9"
white_alt="#ffffff"

active_border="#424242"

grey="#373b41"

border_width=2
