#!/bin/bash

#                                                                               | limit
echo -ne '\e[32m'
cat << EOF

 ##############################################################################
 #                                                                            #
 #                                                                            #
 #                                                                            #
 #                      Welcome to your computer, sir.                        #
 #                                                                            #
 #                                                                            #
 #                                                                            #
 ##############################################################################

EOF
echo -ne '\e[m'

export terminal="logon"
bash
export terminal=""
