#!/usr/bin/python

import sys
import serial

device = "/dev/ttyUSB0"
bauds = 9600

if len(sys.argv) >= 3:
    bauds = int(sys.argv[2])
elif len(sys.argv) >= 2:
    device = sys.argv[1]

try:
    ser = serial.Serial(device, bauds)
except:
    print("Error.")
    exit(0)

while True:
    try:
        sys.stdout.write(ser.read(1).decode('utf-8'))
        sys.stdout.flush()
    except KeyboardInterrupt:
        print("\rInterrupt signal received.")
        exit(0)

sys.stdout.write('\n')
