#!/usr/bin/python

import time
import sys

def print_anim(text, delay = 0.03):
    for c in text:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write('\n')

if __name__ == "__main__":
    while 1:
        try:
            print_anim(input())
        except EOFError:
            break
    
    #print_anim(" ".join(list(sys.argv[1::])))
