#! /bin/sh

. ~/.config/colors/$_THEME

bspc config border_width        $border_width
bspc config window_gap          4

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "$black_alt"
bspc config active_border_color "$black_alt"
bspc config focused_border_color "$green_alt"
bspc config presel_border_color "$yellow_alt"
bspc config urgent_border_color "$red_alt"
bspc config focused_locked_border_color "$blue"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config top_padding         15

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{1,2,3,4,5,6,7,8,9}
    let i++
done
NMON=$i
unset i

panel &
